### PR TITLE
Fix init+exit order as `usbi_hotplug` depends on `usbi_backend`

### PR DESCRIPTION
**Pull request by CraigHutchinson**
This resolves issue introduced in https://github.com/xloem/libusb/pull/3#issuecomment-1096869875 with root cause https://github.com/libusb/libusb/pull/874#issuecomment-1097703408

1. `usbi_hotplug_init` has been moved to after `usbi_backend.init` for the circumstance the backend is used during Hotplug initialise (not currently the case)
2. exit is in the reverse order, `usbi_hotplug_exit` occurs prior to `usbi_backend.exit` for the existing circumstance that the `android_jni` backend is used during hotplug exit.

### CODE REVIEW

**Comment by CraigHutchinson** [comment]
@xloem @themarpe  I cannot assign reviewers but can you check please, I cannot see any negative repercussions of the sequencing other than to make more logical sense to me.

**Comment by xloem** [comment]
This change looks familiar to me. I think it may already be in libusb master.

**Comment by CraigHutchinson** [comment]
Yes, you are correct.
https://github.com/libusb/libusb/blob/4239bc3a50014b8e6a5a2a59df1fff3b7469543b/libusb/core.c#L2356

So if the Android branch were updated against master the aforementioned issue would be resolved 👍

**Comment by CraigHutchinson** [comment]
Closing as duplicate of changes on `master` from https://github.com/libusb/libusb/commit/0846456f3a9fda8ff5469d9d0b9700837ff16f04

**Comment by CraigHutchinson** [comment]
CORRECTION: The existing change on master only resolves the `init` phase and does not updated the `exit` phase accordingly.

**Pull request closed without merging**
